### ISSUE TITLE
Small Typo "heirarchy" instead of "hierarchy" (page 8, 5th line from the bottom)

### ISSUE THREAD

**Issue by DominikHolenstein** [leanprover/introduction_to_lean#3]
**Introduction to Lean - Chatper 1**
I have just found a small Typo: 
Is: "heirarchy"
should be: "hierarchy" 

(PDF version: page 8, 5th text line from the bottom).

Best,
Dominik

**Comment by avigad** [comment]
closed 59d4dbb. Thanks!
